/* Generated by Myra UI Editor at 12/28/2018 12:19:18 PM */
using Myra.Graphics2D.UI;

namespace Tank.Content	
{
	public partial class MainMenu: Panel
	{
		public MainMenu()
		{
			BuildUI();
		}
	}
}