/* Generated by Myra UI Editor at 12/28/2018 12:19:18 PM */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Tank.Content	
{
	partial class MainMenu
	{
		private void BuildUI()
		{
			Reset = new MenuItem();
			Reset.Id = "Reset";
			Reset.Text = "Reset";

			var menuSeparator1 = new MenuSeparator();

			Quit = new MenuItem();
			Quit.Id = "Quit";
			Quit.Text = "Quit";

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.Items.Add(Reset);
			horizontalMenu1.Items.Add(menuSeparator1);
			horizontalMenu1.Items.Add(Quit);

			
			Widgets.Add(horizontalMenu1);
		}

		
		public MenuItem Reset;
		public MenuItem Quit;
	}
}